WIP: refactor: allow multiple checkMaterials in contrustor of MaterialMult…
Plugily-Projects/MiniGamesBox pull request #10
Opened 2022-08-10 20:03 UTC by VerschuerenTom

…iLocationItem

2022-08-10 20:18 UTC, VerschuerenTom commented
Needs testing

2022-08-10 20:19 UTC, Tigerpanzer02 requested changes
Getting the targetblock type would be enough for the end user about materials ;)

2022-08-10 20:19 UTC, Tigerpanzer02 commented on MiniGamesBox Classic/src/main/java/plugily/projects/minigamesbox/classic/handlers/setup/items/category/MaterialMultiLocationItem.java
> +          new MessageBuilder("You can now remove the " + checkMaterials.toString() + "!").prefix().send(player);
could return unreadable long message for user, getting the "clicked" type would be more accurate

2022-08-10 20:19 UTC, Tigerpanzer02 commented on MiniGamesBox Classic/src/main/java/plugily/projects/minigamesbox/classic/handlers/setup/items/category/MaterialMultiLocationItem.java
> +                        + " &cand location you want to place is in radius of this protection! &c&lNon opped players won't be able to interact with this " + checkMaterials + " and can't join the game!
could return unreadable long message for user, getting the "clicked" type would be more accurate

2022-08-10 20:19 UTC, Tigerpanzer02 commented on MiniGamesBox Classic/src/main/java/plugily/projects/minigamesbox/classic/handlers/setup/items/category/MaterialMultiLocationItem.java
> +                new MessageBuilder("&c&l✘ &cPlease only use location where already is a " + checkMaterials + " to add it as a " + name.toUpperCase() + "!").prefix().send(interactEvent.getPlayer());
could return unreadable long message for user, getting the "clicked" type would be more accurate

2022-08-10 20:19 UTC, Tigerpanzer02 commented on MiniGamesBox Classic/src/main/java/plugily/projects/minigamesbox/classic/handlers/setup/items/category/MaterialMultiLocationItem.java
> +                new MessageBuilder("&c&l✘ &cPlease only use location where already is a " + checkMaterials+ " to remove it as a " + name.toUpperCase() + "!").prefix().send(interactEvent.getPlayer());
could return unreadable long message for user, getting the "clicked" type would be more accurate

2022-08-10 20:19 UTC, Tigerpanzer02 commented on MiniGamesBox Classic/src/main/java/plugily/projects/minigamesbox/classic/handlers/setup/items/category/MaterialMultiLocationItem.java
> +              new MessageBuilder("&c&l✘ &cYou can't use a location that is at your player location, please select the " + checkMaterials.toString() + "!").prefix().send(interactEvent.getPlayer());
could return unreadable long message for user, getting the "clicked" type would be more accurate

2022-08-10 20:19 UTC, Tigerpanzer02 commented on MiniGamesBox Classic/src/main/java/plugily/projects/minigamesbox/classic/handlers/setup/items/category/MaterialMultiLocationItem.java
> +          new MessageBuilder("&c&l✘ &cPlease only look at a location where already is a " + checkMaterials+ " to add it as a " + name.toUpperCase() + "!").prefix().send(event.getWhoClicked());
could return unreadable long message for user, getting the "clicked" type would be more accurate

2022-08-12 18:48 UTC, Tigerpanzer02 commented
@VerschuerenTom Waiting for your adjustments ;)

2022-08-24 09:42 UTC, Tigerpanzer02 commented
implemented on my own as no respone

2022-08-24 09:42 UTC, closed without merging